config/routes.rb
Rails.application.routes.draw do
  resources :tables
  resources :orders
  resources :food_types
  get 'home/about_us'
 
  get 'home/menus'
  get 'home/talk_to_us'
  get 'home/orders'



  

    
   resources :menus

	root 'home#about_us'
	

	
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_group.rb
class FoodGroup < ApplicationRecord
    has_many :food_types
	def self.all
		%w( Breakfast Lunch Dinner Beverages desserts)
   end 
end

app/models/food_type.rb
class FoodType < ApplicationRecord
	belongs_to :food_group
	validates :name , :about, :price, presence: true

	def image_url
		if remote_image_url.present?
			remote_image_url
		end
	end
end

app/models/menus.rb
class Menus < ApplicationRecord
	has_many :food_groups
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :table
end

app/models/table.rb
class Table < ApplicationRecord
	has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_types_controller.rb
class FoodTypesController < ApplicationController
  before_action :set_food_type, only: [:show, :edit, :update, :destroy]

  # GET /food_types
  # GET /food_types.json
  def index
    @food_types = FoodType.all
  end

  # GET /food_types/1
  # GET /food_types/1.json
  def show
  end

  # GET /food_types/new
  def new
    @food_type = FoodType.new
  end

  # GET /food_types/1/edit
  def edit
  end

  # POST /food_types
  # POST /food_types.json
  def create
    @food_type = FoodType.new(food_type_params)

    respond_to do |format|
      if @food_type.save
        format.html { redirect_to @food_type, notice: 'Food type was successfully created.' }
        format.json { render :show, status: :created, location: @food_type }
      else
        format.html { render :new }
        format.json { render json: @food_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_types/1
  # PATCH/PUT /food_types/1.json
  def update
    respond_to do |format|
      if @food_type.update(food_type_params)
        format.html { redirect_to @food_type, notice: 'Food type was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_type }
      else
        format.html { render :edit }
        format.json { render json: @food_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_types/1
  # DELETE /food_types/1.json
  def destroy
    @food_type.destroy
    respond_to do |format|
      format.html { redirect_to food_types_url, notice: 'Food type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_type
      @food_type = FoodType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_type_params
      params.require(:food_type).permit(:name, :about, :price, :food_group, :remote_image_url, :food_group_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def about_us
  end

  def menus 
   if params[:food_group]
  		@food_types = FoodType.where food_group: params[:food_group]
  	else
  		@food_types = FoodType.all
  	end
  end 


  def talk_to_us
  end
 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:food_type, :food_group, :table_no, :price, :total)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:table_no)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_types_helper.rb
module FoodTypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/food_types/_form.html.erb
<%= form_for(food_type) do |f| %>
  <% if food_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_type.errors.count, "error") %> prohibited this food_type from being saved:</h2>

      <ul>
      <% food_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'form-control-label'%>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :about, class: 'form-control-label'%>
    <%= f.text_field :about, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :food_group %>
    <%= f.text_field :food_group %>
  </div>

  <div class="form-group">
    <%= f.label :remote_image_url %>
    <%= f.text_field :remote_image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_types/edit.html.erb
<h1>Editing Food Type</h1>

<%= render 'form', food_type: @food_type %>

<%= link_to 'Show', @food_type %> |
<%= link_to 'Back', food_types_path %>

app/views/food_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Our Delicacies</h1>

<table class = "table table-striped">
  <thead class = "thead thead-defaultkkmm">
    <tr>
      <th>Name</th>
      <th>About</th>
      <th>Price</th>
      <th>Food group</th>
      <th>Remote image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_types.each do |food_type| %>
      <tr>
        <td><%= food_type.name %></td>
        <td><%= food_type.about %></td>
        <td><%= food_type.price %></td>
        <td><%= food_type.food_group %></td>
        <td><%=image_tag food_type.image_url %></td>

        <td><%= link_to 'Show', food_type %></td>
        <td><%= link_to 'Edit', edit_food_type_path(food_type) %></td>
        <td><%= link_to 'Destroy', food_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Type', new_food_type_path, class: "btn btn-secondary"%>

app/views/food_types/new.html.erb
<h1>New Food Type</h1>

<%= render 'form', food_type: @food_type %>

<%= link_to 'Back', food_types_path %>

app/views/food_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_type.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @food_type.about %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_type.price %>
</p>

<p>
  <strong>Food group:</strong>
  <%= @food_type.food_group %>
</p>

<p>
  <strong>Remote image url:</strong>
  <%= @food_type.remote_image_url %>
</p>

<%= link_to 'Edit', edit_food_type_path(@food_type) %> |
<%= link_to 'Back', food_types_path %>

app/views/home/about_us.html.erb
<div class="jumbotron">
<h1></h1>
<h2> </h2>

 <h1 class="display-3">Welcome to Marie's Restuarant!</h1>

  
           
      

     


</div>
<p class="lead">Here at Marie's your tummy is our guest. Ya'll ready?...Okay! Let's eat! :) </p>
  <hr class="my-4">
  <p class = "lead2">Feel free to browse our menus for our array of Enticingly delicious Foods, Beverages Desserts and more...</p>
  <p class="lead">
   <%= link_to "Our Menus",home_menus_path, class: "btn btn-primary btn-lg"%>
            <%= link_to "Talk to us :)",home_talk_to_us_path, class: "btn btn-primary btn-lg"%>

app/views/home/menus.html.erb
<div class = 'menupage'>

<%=link_to "Menu",home_menus_path%>

<% FoodGroup.all.each do |food_group|%>
	<div class="btn-group" role="group" aria-label="Basic example">
       <%=link_to food_group,home_menus_path(food_group:food_group),class:'btn btn-secondary'%>
    </div>

<% end%>
     <div> </div>
</br>

<%@food_types.each do |food_type|%>
 
 <div class="container">

<div class = "card" style="width: 20rem;>
   <div class = "card-header"> <%= food_type.name%> </div>
   <div class = "card-block">
          <%=image_tag food_type.image_url, class:'image'%>
            <p class="card-text"><%=food_type.about%></p>

               <p><%=food_type.price %></p>
                 <%= link_to "Order Now",home_orders_path, class: "btn btn-primary btn-sm"%>
                  
            </div>
    </div>
</div>

    </div>
    </div>



<%end%>

app/views/home/orders.html.erb
<h1> Make Order</h1>

app/views/home/talk_to_us.html.erb
<div class="row">
	<div class="col-lg-4 col-md-4">
	<h1 id = "contacts"> Our Contacts</h1>
    <p> For any queries and concerns kindly reach us here;</p>
	</div>
</div>
<div class = "row container">
  <div class = "col-xs-4">
   <h3>Address;</h3>
      <address class = "address">
         Marie's Restuarant</br>
         Address:Box 213-0100</br>
         Email:mariesdelight@gmail.com</br>
         Tel: 020-003-698-74
     </address>
</div>
<div class = "col-xs-8">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.764802130845!2d36.83178304993399!3d-1.316714599034934!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f11afa4fb7e35%3A0xe8f3f2adbff0c846!2sCapital+Centre!5e0!3m2!1sen!2s!4v1497178009693" width="700" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrestuarant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="<%=root_path%>">Marie's</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path)%>">
        <a class="nav-link" href="<%=root_path%>"Home <span class="sr-only">Home</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Reservations</a>
      </li>
    
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class = "container"> 
    <%= yield %>
    </div>
  </body>
</html>

app/views/models/_form.html.erb
<%= form_for(model) do |f| %>
  <% if model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :FoodType %>
    <%= f.text_field :FoodType %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_area :about %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :food_group %>
    <%= f.text_field :food_group %>
  </div>

  <div class="field">
    <%= f.label :remote_image_url %>
    <%= f.text_field :remote_image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_type %>
    <%= f.text_field :food_type %>
  </div>

  <div class="field">
    <%= f.label :food_group %>
    <%= f.text_field :food_group %>
  </div>

  <div class="field">
    <%= f.label :table_no %>
    <%= f.number_field :table_no %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class = "table table-striped">
  <thead class = "thead thead-default">
    <tr>
      <th>Food type</th>
      <th>Food group</th>
      <th>Table no</th>
      <th>Price</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.food_type %></td>
        <td><%= order.food_group %></td>
        <td><%= order.table_no %></td>
        <td><%= order.price %></td>
        <td><%= order.total %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food type:</strong>
  <%= @order.food_type %>
</p>

<p>
  <strong>Food group:</strong>
  <%= @order.food_group %>
</p>

<p>
  <strong>Table no:</strong>
  <%= @order.table_no %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/tables/_form.html.erb
<%= form_for(table) do |f| %>
  <% if table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_no %>
    <%= f.number_field :table_no %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tables</h1>

<table>
  <thead>
    <tr>
      <th>Table no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.table_no %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table no:</strong>
  <%= @table.table_no %>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>